### ISSUE TITLE
Melpa package has empty .el source

### ISSUE THREAD

**Issue by jaromil** [jschaf/emacs-lorem-ipsum#3]
Currently on `20140911.1408` if installed from melpa the source package of lorem-ipsum is empty.

**Comment by jschaf** [comment]
I can't reproduce.  I just deleted and reinstalled lorem ipsum and it works as expected.  Are there any errors?  Can you try reinstalling?

Maybe MELPA was down?

**Comment by jaromil** [comment]
Deleted and reinstalled just now and the source is there. Weird, especially if this is the way MELPA reacts to network outages (the package was installed just the `lorem-ipsum.el` source was empty). Thanks.
